// Group extracted prompt lines into coherent source blocks, preserving every line and anchor.
window.APPENDIX_BLOCKS={
57:[
[2,2,'Sample construction','The sampling frame is articles in five named journals from 2000–2025. Excluding proceedings, early-access records, and retractions determines the denominator before any cognitive-topic classification happens. Supplementing missing abstracts improves the material available to the classifier; it does not expand the journal sample.'],
[3,3,'Classification and figure weights','The first pass assigns inclusion, topics, methods, and field; the second audits behavioral inclusion. Figure 1 uses the primary topic in its upper panels, but divides a paper’s weight among its research-design labels in the bottom-right panel. A paper with two design labels contributes half to each. Gender is merged with Other only for the visualization.'],
[4,9,'First-pass system prompt','This reproduced prompt restricts the classifier to titles and abstracts, excluding author reputation and journal identity. It asks for a reasoning section and a structured result, and biases ambiguous decisions toward exclusion. These are the author’s classification instructions, reproduced as evidence about the method.'],
[10,12,'First-pass record','The first field is a yes/no gate for inclusion in behavioral economics. Topic, method, and field labels follow on page 58. Keeping an explicit inclusion flag lets the pipeline distinguish a nonbehavioral paper from a behavioral paper outside the named topic categories.']],
58:[
[0,3,'Output fields','The output separates what a paper studies, how it studies it, and its applied field. The sample JSON illustrates inclusion and category fields but does not show research_type_labels, even though the preceding instructions request that field. This is a discrepancy in the reproduced specification, not evidence about what the actual stored records contain.'],
[4,14,'Behavioral inclusion gate','A psychological concept must be central. Studying beliefs, imperfect information, or a departure from a benchmark is not automatically enough. Rejected papers receive no topic or field assignment; accepted ones continue to categorization. The procedure deliberately separates an economic setting from a behavioral mechanism.'],
[15,19,'Two first-pass routes to inclusion','The first pass permits either an explicitly central psychological mechanism or a central test of deviation from a rational benchmark. Notice the OR condition: a paper can satisfy one without the other. This matters when comparing the stricter audit rule on page 63.'],
[20,22,'Exclusion override begins','The override asks whether ordinary adjustment, frictions, or measurement can explain the main pattern. Its final condition continues on page 59: the abstract must also lack an explicitly named psychological mechanism or bias. The word override gives this rule priority over a loose reading of a benchmark deviation.']],
59:[
[0,9,'Phrases that do not establish behavioral content','This completes the exclusion override. Words such as beliefs, wedges, sticky adjustment, or information costs do not themselves establish a psychological explanation. Even inattention and salience can be used as economic-friction labels; the prompt asks for their behavioral interpretation or an explicit behavioral test.'],
[10,17,'Primary versus secondary topics','Two categories are allowed only when both are central, and their order records importance rather than alphabetical order. Since the trend figure uses the first category, changing that ordering can change measured topic shares even without changing which papers enter the sample. Other is reserved for behavioral papers fitting none of the named categories.'],
[18,27,'What counts as cognitive','The cognitive label requires an identifiable channel such as memory, complexity, analogy, or an incorrect mental model. Generic bounded rationality or a generic mistake is insufficient. This operational definition shapes the measured cognitive share: an abstract can discuss nonstandard behavior without naming enough of its mechanism to qualify.'],
[28,30,'Social category begins','The definition begins with motives such as altruism, fairness, and reciprocity. It continues on page 60 with norms and identity. The list concerns why people value outcomes or act, rather than whether the setting happens to involve other people.']],
60:[
[0,3,'Social motives versus social settings','The continuation includes moral preferences, identity, and norms, then excludes labels such as social networks or social insurance when no such motive is central. The category is about a mechanism or outcome of interest, not the presence of the word social.'],
[4,10,'Risk and time category','This category covers central contributions about risk, ambiguity, probability weighting, reference dependence, or intertemporal preferences. A paper using risky assets as its setting is not enough: it must estimate or test the relevant preference components or behavioral patterns.'],
[11,18,'Biases category','The definition covers specific systematic errors or paradoxes as core contributions. Its final instruction discourages assigning Biases to a paper whose specific cognitive mechanism is better captured by Cognitive. Thus topic classification partly encodes the level of explanation, not just the presence of an anomalous result.'],
[19,24,'Strategic category','Behavioral strategic reasoning must be central: for example, limited reasoning depth, noisy best response, or a behavioral equilibrium model. A standard auction or industrial-organization paper does not qualify merely because its agents interact strategically.'],
[25,27,'Gender category','Gender must be a central explanatory variable, as in preferences, identity, stereotypes, or discrimination. Including gender as a background characteristic does not suffice. This topic is later combined with Other in the figure, as described on page 57.'],
[28,33,'Methods and theory label','Method labels describe evidence rather than topic, and can overlap. Theory requires a core theoretical contribution, including proofs or a model studied analytically or by simulation. The qualification continues on page 61: a mainly empirical paper does not become Theory simply by mentioning a motivating model.']],
61:[
[0,1,'Theory qualification','This completes the Theory definition from page 60. It distinguishes a primarily model-based contribution from empirical estimation that merely cites a model as motivation. The rule avoids treating almost every economic paper as theoretical.'],
[2,7,'Experimental evidence label','Despite its name, LAB_OR_ONLINE_EXPERIMENT includes randomized field experiments, survey experiments, and other researcher-assigned treatments. Natural or quasi-experiments using observational data are excluded from this label. Interpreting the plotted design shares therefore requires reading the operational definition rather than the label alone.'],
[8,13,'Observational evidence label','The definition includes administrative and survey data as well as identification methods such as IV, regression discontinuity, and difference-in-differences. Observational here means the researcher does not randomize treatment. It does not mean a paper lacks a causal identification strategy.'],
[14,18,'Overlapping methods','A paper can develop a model and also use experimental or observational evidence. Randomized survey vignettes count as experiments; descriptive survey analysis counts as observational. These overlaps explain why Figure 1 divides each paper’s weight among its assigned design categories.'],
[19,22,'One field per included paper','Field classification is conditional on behavioral inclusion and allows exactly one field. This differs from topic and method labels, which can overlap. A nonbehavioral record receives a null field rather than being assigned to Abstract/Mechanism by default.'],
[23,28,'Abstract or mechanism field','This field covers contributions whose principal target is a general mechanism, decision-theoretic insight, or method rather than a specific applied domain. A laboratory experiment can still be applied if its main question is tied to such a domain; laboratory format alone does not decide the field.'],
[29,31,'Applied micro field','The examples include labor, health, development, household behavior, and firms in particular markets. They classify the economic domain of the main contribution, independently of whether the paper uses experiments, observational data, or theory.'],
[32,33,'Finance field','The domain includes assets, trading, banking, credit, and household finance. The tie-breaker on page 62 gives finance precedence when financial assets or institutions are central, even if the methods are microeconomic.']],
62:[
[0,1,'Macro field','The macro definition covers aggregate fluctuations, policy, growth, equilibrium models, and expectations. A survey about inflation can enter this field, but only after it separately passes behavioral inclusion. Mentioning expectations never bypasses the earlier gate.'],
[2,5,'Field tie-breakers','Finance takes precedence for a contribution centered on assets or banks; Macro applies to aggregate policy or dynamics; clearly micro-applied questions receive Applied Micro. Abstract/Mechanism is the residual in this tie-breaking instruction. These priorities affect field shares for papers spanning domains.'],
[6,10,'Consistency checks','These checks enforce allowed combinations: rejected papers have empty topics and no field; accepted papers have one or two topics; Other cannot be combined with another topic. Methods may be missing when the abstract does not reveal them. Structural consistency does not establish substantive classification accuracy.'],
[11,13,'Batch-size consistency','The prompt asks the classifier to apply the same inclusion standard regardless of batch size and to exclude doubtful cases. This addresses a possible source of variation in classification; a written instruction alone does not show that batch effects were measured or eliminated.'],
[14,16,'First-pass output and input','Each explanation and structured record is keyed to an input paper. The placeholder at the end describes the title-and-abstract records supplied to the model. Primary and secondary labels must be explicit so their ordering can be recovered for the figure.'],
[17,24,'Second-pass system prompt','The audit is deliberately skeptical and only revisits papers already classified as behavioral. It can remove first-pass inclusions, but this setup does not recover papers wrongly excluded in the first pass. A second model instance is an additional screen, not an independent human validation sample.'],
[25,27,'Audit task begins','This starts the audit’s decision instruction and continues on page 63. The output is confirmation or rejection of behavioral inclusion, rather than a fresh assignment of all topic, method, and field categories.']],
63:[
[0,6,'Named and central mechanism','The audit’s first two questions require a specifically named psychological mechanism and require it to be central. A passing mention is insufficient. The initial word on this page completes the confirmation/rejection instruction begun on page 62.'],
[7,9,'Could standard theory suffice?','Question 3 asks whether rational agents with standard preferences and ordinary frictions could explain the main contribution. A yes answer counts against behavioral inclusion under this audit. This is a demanding conceptual screen that may be difficult to resolve from an abstract alone.'],
[10,17,'Common false-positive domains','The audit lists information economics, heterogeneous beliefs, standard frictions, and related subjects that can be mistaken for behavioral work. The issue is their use without a behavioral mechanism, not that these economic domains can never contain behavioral research.'],
[18,19,'The audit uses an AND rule','Confirmation requires all four conditions: a named mechanism, centrality, insufficiency of standard theory, and absence of the listed misclassification. This is stricter than the first pass’s alternative routes to inclusion. An audit rejection therefore need not imply that the first pass ignored its own written rule.'],
[20,23,'Rejected expectations example begins','The synthetic example studies the link between inflation expectations and spending. Its continuation on page 64 is rejected because it names no psychological mechanism. The quoted abstract is a prompt illustration, not a cited empirical study or a finding produced by the review.']],
64:[
[0,2,'Why the expectations example fails','This completes the example from page 63. The prompt classifies an expectations–spending association as insufficient because standard theory can accommodate it and no psychological mechanism is named. It illustrates the boundary between studying beliefs and studying a behavioral bias in beliefs.'],
[3,7,'Why the housing example fails','Search intensity and information asymmetry explain price dispersion in the hypothetical housing abstract. The audit rejects it as standard information/search economics. The example teaches that a costly-information setting alone does not meet this classifier’s behavioral definition.'],
[8,12,'Why the disagreement example fails','Professional forecasters disagree in this example, but the abstract does not attribute disagreement to a named psychological bias. The audit rejects it. Heterogeneity of beliefs is an outcome that can arise in both standard and behavioral accounts.'],
[13,18,'Why present bias passes','The hypothetical credit-card example explicitly makes present bias central to overborrowing, so the checklist confirms it. The figure of 40% is part of the illustrative prompt text, not a documented estimate from the review. The final line starts the next example, about labor supply.'],
[19,22,'Why loss aversion passes','The taxi-driver example explicitly tests reference-dependent preferences around an income target. Naming and centrally testing that mechanism satisfies the audit in a way that generic labor-supply behavior would not. This is another prompt example rather than a bibliographic entry.'],
[23,24,'Audit reasoning format','The template stores each answer to the four audit questions and the resulting decision beside the paper’s key. It makes the classifier’s stated reason inspectable, though an intelligible reason can still accompany an incorrect label.']],
65:[
[0,4,'Audit result fields','The audit returns confirmation as a Boolean and a short rejection reason, using null for a confirmed paper. Unlike the first-pass record, it does not request a new full topic assignment. This documents the output format, not the observed number or composition of rejected papers.'],
[5,6,'What the audit receives','Along with the title and abstract, the audit receives the original first-pass categories. It therefore has access to earlier classification information. A second instance does not necessarily provide an independent judgment, since it can share both the original framing and the same model’s tendencies.']]
};
function readerBlocks(page){
 const groups=APPENDIX_BLOCKS[page.number];if(!groups)return page.paragraphs;
 const starts=new Map(groups.map(g=>['p'+page.number+'-'+g[0],g]));const consumed=new Set();const result=[];
 for(const p of page.paragraphs){if(consumed.has(p.id))continue;const g=starts.get(p.id);if(!g){result.push(p);continue;}
 const source=page.paragraphs.filter(x=>{const i=Number(x.id.split('-')[1]);return i>=g[0]&&i<=g[1]});source.forEach(x=>consumed.add(x.id));
 result.push({...p,heading:false,text:source.map(x=>x.text).join('\n'),sourceIds:source.map(x=>x.id),refs:[...new Set(source.flatMap(x=>x.refs||[]))],annotation:g[3],annotationTitle:g[2]});
 }return result;
}
